#!/usr/bin/python

import os, sys
import getopt
import json
from shutil import copy
import mbed_util, config

disk = mbed_util['board_flash']
serial_port = "/dev/tty.usbmodem1423"
serial_baudrate = 9600

opts, args = getopt.getopt(sys.argv[1:], "d:p:b:")
for o,a in opts:
    if o in ['-d']:
        disk = a
    elif o in ['-p']:
        serial_port = a
    elif o in ['-b']:
        serial_baudrate = int(a)

package_json_file = open("./package.json", 'r')
package_info = json.loads(package_json_file.read())
package_json_file.close()

print "Compiling ..."
if os.system('make') == 1: sys.exit()
print "Compile complete"
print "Downloading ..."
copy("./%s.bin" % package_info['name'], disk)
print "Download complete"
print "Running...\n"
if os.system('python /Users/zhangcosmo/work/python/comm.py %s %d' % (serial_port, serial_baudrate)): sys.exit()






